#!/usr/bin/env bash
# Install BEHAVIOR-1K conda env "behavior" — idempotent, non-interactive.
#
# Layout choices (kept here, not in the notebook, so callers stay 1-line):
#   - submodule path:        dependencies/BEHAVIOR-1K
#   - conda env name:        behavior
#   - dataset path:          $OMNIGIBSON_DATA_PATH (default $HOME/.cache/omnigibson)
#     persisted via <env>/etc/conda/activate.d/omnigibson.sh
#
# Run from any CWD inside the repo; we cd to git root.

set -euo pipefail

ENV_NAME="${BEHAVIOR_ENV_NAME:-behavior}"
SUBMOD="dependencies/BEHAVIOR-1K"

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

# ---------- 0. shared dataset dir ---------------------------------------------
export OMNIGIBSON_DATA_PATH="${OMNIGIBSON_DATA_PATH:-$HOME/.cache/omnigibson}"
mkdir -p "$OMNIGIBSON_DATA_PATH"
echo ">>> OMNIGIBSON_DATA_PATH=$OMNIGIBSON_DATA_PATH"

# ---------- 1. submodule ------------------------------------------------------
if [[ ! -f "$SUBMOD/setup.sh" ]]; then
  echo ">>> init submodule $SUBMOD ..."
  git submodule update --init "$SUBMOD"
fi

# ---------- 2. locate conda ---------------------------------------------------
CONDA_BIN="${CONDA_EXE:-$(command -v conda || true)}"
if [[ -z "$CONDA_BIN" ]]; then
  echo "ERROR: conda not found in PATH or \$CONDA_EXE" >&2
  exit 1
fi
CONDA_BASE="$("$CONDA_BIN" info --base)"
# shellcheck disable=SC1091
source "$CONDA_BASE/etc/profile.d/conda.sh"

# ---------- 3. run setup.sh if env missing -----------------------------------
ENV_DIR="$CONDA_BASE/envs/$ENV_NAME"
if conda env list | awk '{print $1}' | grep -qx "$ENV_NAME"; then
  echo ">>> conda env [$ENV_NAME] exists, skip setup.sh"
else
  echo ">>> running BEHAVIOR-1K setup.sh (non-interactive) ..."
  pushd "$SUBMOD" >/dev/null
  bash setup.sh \
    --new-env "$ENV_NAME" \
    --omnigibson --bddl --dataset --joylo \
    --accept-conda-tos --accept-nvidia-eula --accept-dataset-tos
  popd >/dev/null
fi

# ---------- 4. persist OMNIGIBSON_DATA_PATH in activate hook ------------------
ACT_DIR="$ENV_DIR/etc/conda/activate.d"
mkdir -p "$ACT_DIR"
cat > "$ACT_DIR/omnigibson.sh" <<EOF
# auto-generated by scripts/install_behavior_env.sh
export OMNIGIBSON_DATA_PATH="\${OMNIGIBSON_DATA_PATH:-\$HOME/.cache/omnigibson}"
# Workaround: CPython 3.11 + torch.compile + hipify trie-regex →
# intermittent UnboundLocalError in re._parser. OmniGibson uses
# @torch_compile only for speed; disabling is safe.
export TORCH_COMPILE_DISABLE="\${TORCH_COMPILE_DISABLE:-1}"
EOF
echo ">>> wrote activate hook: $ACT_DIR/omnigibson.sh"

# ---------- 5. ensure datasets are downloaded ---------------------------------
# setup.sh may have been skipped (env existed) or aborted mid-way before datasets.
# Drive the official downloaders directly — they print "already installed" and
# skip if the target dir already exists.
conda activate "$ENV_NAME"
export OMNI_KIT_ACCEPT_EULA=YES
python - <<'PY'
import os
from omnigibson.utils.asset_utils import (
    download_omnigibson_robot_assets,
    download_behavior_1k_assets,
    get_dataset_path,
)
print(f"OMNIGIBSON_DATA_PATH = {os.environ.get('OMNIGIBSON_DATA_PATH')}")
print(f"behavior-1k-assets target = {get_dataset_path('behavior-1k-assets')}")
download_omnigibson_robot_assets()
download_behavior_1k_assets(accept_license=True)
PY

# ---------- 6. smoke test -----------------------------------------------------
python - <<'PY'
import omnigibson, os
print(f"OmniGibson: {omnigibson.__version__}")
print(f"OMNIGIBSON_DATA_PATH: {os.environ.get('OMNIGIBSON_DATA_PATH')}")
PY
echo ">>> behavior env ready"
